FROM node:22.3.0-alpine3.19

# create working directory
WORKDIR /kashafty/client

# COPY package*.json ./

# RUN npm install
# COPY . .
# RUN npm run build

# expose port
# EXPOSE 4173
EXPOSE 3001

# run the app
# notice this is made for dev
# when production change dev to preview
CMD ["npm", "run", "dev"]
