version: '3.8'

services:
  db:
    build: ./server/database/.
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: amir.kedis@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin

  frontend:
    build: ./client/.
    restart: always
    ports:
      - 4173:4173
    environment:
      VITE_API_URL: http://localhost:5000
    volumes:
      - ./client/node_modules:/kashafty/client/node_modules
      - ./client/public:/kashafty/client/public
      - ./client/src:/kashafty/client/src
      - ./client/package.json:/kashafty/client/package.json
  
  backend:
    build: ./server/.
    restart: always
    ports:
      - 5000:5000
    environment:
      FRONTEND_URL: http://localhost:4173
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    volumes:
      - ./server/node_modules:/kashafty/server/node_modules
      - ./server/src:/kashafty/server/src
      - ./server/package.json:/kashafty/server/package.json
    depends_on:
      - db

  # web:
  #   build: .
  #   ports:
  #     - 3001:3001
  #     - 5000:5000
  #   environment:
  #     # - DATABASE_URL=postgres://<user>:<password>@<host>:<port>/<database>
  #     - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
  #   depends_on:
  #     - db
  #     - pgadmin
  #   # TODO: remove or refactor for production
  #   # those are used just for hot reolad and
  #   # node modules caching
  #   volumes:
  #     # - source: ./server
  #     #   target: /kashafty/server
  #     #   type: bind
  #     # - source: ./client
  #     #   target: /kashafty/client
  #     #   type: bind
  #     - source: .
  #       target: /kashafty
  #       type: bind
  #     - source: ./node_modules
  #       target: /kashafty/node_modules
  #       type: bind
  #     - source: ./client/node_modules
  #       target: /kashafty/client/node_modules
  #       type: bind
