services:
  db:
    build: ./server/database/.
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: amir.kedis@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin

  frontend:
    build: ./client/.
    restart: always
    ports:
      - 4173:4173
      - 3000:3000
      - 3001:3001
    environment:
      VITE_API_URL: http://localhost:5000
    volumes:
      - ./client:/kashafty/client
      - ./client/node_modules:/kashafty/client/node_modules
  
  backend:
    build: ./server/.
    restart: always
    ports:
      - 5000:5000
    environment:
      FRONTEND_URL: http://localhost:4173
    volumes:
      - ./server:/kashafty/server
    depends_on:
      - db
