FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

# Copy prisma schema
COPY prisma ./prisma/

# Generate Prisma client
RUN npx prisma generate

COPY . .

EXPOSE 5000

CMD ["npm", "run", "start"]
